// <auto-generated />
using System;
using Northstar.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Northstar.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260410224750_fixedAddressNullableTypes")]
    partial class fixedAddressNullableTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Northstar.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Workspace"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Tech Accessories"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Organization"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Travel"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Home Essentials"
                        });
                });

            modelBuilder.Entity("Northstar.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Apex Office Solutions"
                        },
                        new
                        {
                            Id = 2,
                            Name = "HarborTech Wholesale"
                        },
                        new
                        {
                            Id = 3,
                            Name = "ModuLiving Distributors"
                        },
                        new
                        {
                            Id = 4,
                            Name = "TransitPro Supply"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Hearth & Home Trade"
                        });
                });

            modelBuilder.Entity("Northstar.Models.OrderHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Carrier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("OrderTotal")
                        .HasColumnType("float");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("PaymentDueDate")
                        .HasColumnType("date");

                    b.Property<string>("PaymentIntentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ShippingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("OrderHeaders");
                });

            modelBuilder.Entity("Northstar.Models.OrderItemDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("OrderHeaderId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderHeaderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Northstar.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DiscountPrice")
                        .HasColumnType("float");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Northstar Studio",
                            CategoryId = 1,
                            Description = "Elevated aluminum monitor stand designed to create a cleaner desk setup and improve everyday screen ergonomics.",
                            DiscountPrice = 79.0,
                            ISBN = "NSS-WS-001",
                            Price = 89.0,
                            Title = "Arc Monitor Stand"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Luma Works",
                            CategoryId = 1,
                            Description = "Minimal LED desk lamp with an adjustable neck and warm ambient lighting for focused work sessions.",
                            DiscountPrice = 69.0,
                            ISBN = "NSS-WS-002",
                            Price = 79.0,
                            Title = "Ridge Desk Lamp"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Atlas Goods",
                            CategoryId = 1,
                            Description = "Soft-touch desk mat that anchors keyboards, mice, and notebooks while adding a refined layer to the workspace.",
                            DiscountPrice = 29.0,
                            ISBN = "NSS-WS-003",
                            Price = 35.0,
                            Title = "Atlas Desk Mat"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Pivot Labs",
                            CategoryId = 1,
                            Description = "Foldable laptop riser built for better posture, cleaner airflow, and flexible work-from-home setups.",
                            DiscountPrice = 52.0,
                            ISBN = "NSS-WS-004",
                            Price = 59.0,
                            Title = "Pivot Laptop Riser"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Harbor Works",
                            CategoryId = 2,
                            Description = "Slim wireless keyboard with a clean layout and quiet typing feel, designed for modern desk setups.",
                            DiscountPrice = 89.0,
                            ISBN = "NSS-TA-001",
                            Price = 99.0,
                            Title = "Harbor Wireless Keyboard"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Harbor Works",
                            CategoryId = 2,
                            Description = "Compact wireless mouse with an ergonomic silhouette and smooth tracking for daily productivity.",
                            DiscountPrice = 43.0,
                            ISBN = "NSS-TA-002",
                            Price = 49.0,
                            Title = "Harbor Wireless Mouse"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Signal Labs",
                            CategoryId = 2,
                            Description = "Multi-port USB-C hub that expands laptop connectivity with a sleek footprint for travel or desk use.",
                            DiscountPrice = 61.0,
                            ISBN = "NSS-TA-003",
                            Price = 69.0,
                            Title = "Signal USB-C Hub"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Dockline Systems",
                            CategoryId = 2,
                            Description = "Streamlined charging station for phones, earbuds, and accessories, built to reduce cable clutter.",
                            DiscountPrice = 69.0,
                            ISBN = "NSS-TA-004",
                            Price = 79.0,
                            Title = "Dockline Charging Station"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Fold Home",
                            CategoryId = 3,
                            Description = "Set of collapsible storage boxes that helps keep shelves, closets, and work areas visually organized.",
                            DiscountPrice = 33.0,
                            ISBN = "NSS-OR-001",
                            Price = 39.0,
                            Title = "Fold Storage Box Set"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Grid House",
                            CategoryId = 3,
                            Description = "Modular drawer organizer designed for office supplies, personal accessories, and small everyday items.",
                            DiscountPrice = 25.0,
                            ISBN = "NSS-OR-002",
                            Price = 29.0,
                            Title = "Grid Drawer Organizer"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Stack Office",
                            CategoryId = 3,
                            Description = "Layered document tray with a clean silhouette for sorting paperwork, notebooks, and incoming mail.",
                            DiscountPrice = 28.0,
                            ISBN = "NSS-OR-003",
                            Price = 34.0,
                            Title = "Stack Document Tray"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Rail Utility",
                            CategoryId = 3,
                            Description = "Simple wall-mounted hook rack for entryways, offices, and utility spaces that need practical storage.",
                            DiscountPrice = 26.0,
                            ISBN = "NSS-OR-004",
                            Price = 32.0,
                            Title = "Rail Wall Hook Rack"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Transit Co.",
                            CategoryId = 4,
                            Description = "Daily carry backpack with a streamlined profile, laptop compartment, and versatile storage for commuting.",
                            DiscountPrice = 115.0,
                            ISBN = "NSS-TR-001",
                            Price = 129.0,
                            Title = "Transit Carry Backpack"
                        },
                        new
                        {
                            Id = 14,
                            Author = "Harbor Works",
                            CategoryId = 4,
                            Description = "Protective laptop sleeve with a minimalist exterior and soft inner lining for daily transport.",
                            DiscountPrice = 39.0,
                            ISBN = "NSS-TR-002",
                            Price = 45.0,
                            Title = "Harbor Laptop Sleeve"
                        },
                        new
                        {
                            Id = 15,
                            Author = "Roam Supply",
                            CategoryId = 4,
                            Description = "Compact organizer pouch for chargers, passports, toiletries, and other travel essentials.",
                            DiscountPrice = 24.0,
                            ISBN = "NSS-TR-003",
                            Price = 28.0,
                            Title = "Roam Travel Pouch"
                        },
                        new
                        {
                            Id = 16,
                            Author = "Summit Goods",
                            CategoryId = 4,
                            Description = "Insulated stainless steel bottle that keeps drinks at the right temperature through commutes and day trips.",
                            DiscountPrice = 27.0,
                            ISBN = "NSS-TR-004",
                            Price = 33.0,
                            Title = "Summit Insulated Bottle"
                        },
                        new
                        {
                            Id = 17,
                            Author = "Vale Living",
                            CategoryId = 5,
                            Description = "Soft ambient table lamp created to bring warmth and calm lighting into bedrooms, living rooms, and reading corners.",
                            DiscountPrice = 64.0,
                            ISBN = "NSS-HE-001",
                            Price = 74.0,
                            Title = "Vale Ambient Lamp"
                        },
                        new
                        {
                            Id = 18,
                            Author = "Hearth Studio",
                            CategoryId = 5,
                            Description = "Everyday catch-all tray for keys, wallets, candles, and small essentials that tend to gather around the home.",
                            DiscountPrice = 22.0,
                            ISBN = "NSS-HE-002",
                            Price = 26.0,
                            Title = "Hearth Utility Tray"
                        },
                        new
                        {
                            Id = 19,
                            Author = "Drift Home",
                            CategoryId = 5,
                            Description = "Textured throw blanket designed to add warmth, softness, and a lived-in feel to sofas and beds.",
                            DiscountPrice = 43.0,
                            ISBN = "NSS-HE-003",
                            Price = 49.0,
                            Title = "Drift Throw Blanket"
                        },
                        new
                        {
                            Id = 20,
                            Author = "Grove Living",
                            CategoryId = 5,
                            Description = "Subtle reed diffuser with a clean vessel and balanced fragrance profile for calm interior spaces.",
                            DiscountPrice = 26.0,
                            ISBN = "NSS-HE-004",
                            Price = 31.0,
                            Title = "Grove Reed Diffuser"
                        });
                });

            modelBuilder.Entity("Northstar.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 0,
                            ProductId = 1,
                            Url = "\\images\\products\\arc_monitor_stand\\arc_monitor_stand_01.png"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 1,
                            ProductId = 1,
                            Url = "\\images\\products\\arc_monitor_stand\\arc_monitor_stand_02.png"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 2,
                            ProductId = 1,
                            Url = "\\images\\products\\arc_monitor_stand\\arc_monitor_stand_03.png"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 3,
                            ProductId = 1,
                            Url = "\\images\\products\\arc_monitor_stand\\arc_monitor_stand_04.png"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 0,
                            ProductId = 2,
                            Url = "\\images\\products\\ridge_desk_lamp\\ridge_desk_lamp_01.png"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 1,
                            ProductId = 2,
                            Url = "\\images\\products\\ridge_desk_lamp\\ridge_desk_lamp_02.png"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 2,
                            ProductId = 2,
                            Url = "\\images\\products\\ridge_desk_lamp\\ridge_desk_lamp_03.png"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 3,
                            ProductId = 2,
                            Url = "\\images\\products\\ridge_desk_lamp\\ridge_desk_lamp_04.png"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 0,
                            ProductId = 3,
                            Url = "\\images\\products\\atlas_desk_mat\\atlas_desk_mat_01.png"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 1,
                            ProductId = 3,
                            Url = "\\images\\products\\atlas_desk_mat\\atlas_desk_mat_02.png"
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 0,
                            ProductId = 4,
                            Url = "\\images\\products\\pivot_laptop_riser\\pivot_laptop_riser_01.png"
                        },
                        new
                        {
                            Id = 12,
                            DisplayOrder = 1,
                            ProductId = 4,
                            Url = "\\images\\products\\pivot_laptop_riser\\pivot_laptop_riser_02.png"
                        },
                        new
                        {
                            Id = 13,
                            DisplayOrder = 0,
                            ProductId = 5,
                            Url = "\\images\\products\\harbor_wireless_keyboard\\harbor_wireless_keyboard_01.png"
                        },
                        new
                        {
                            Id = 14,
                            DisplayOrder = 1,
                            ProductId = 5,
                            Url = "\\images\\products\\harbor_wireless_keyboard\\harbor_wireless_keyboard_02.png"
                        },
                        new
                        {
                            Id = 15,
                            DisplayOrder = 2,
                            ProductId = 5,
                            Url = "\\images\\products\\harbor_wireless_keyboard\\harbor_wireless_keyboard_03.png"
                        },
                        new
                        {
                            Id = 16,
                            DisplayOrder = 3,
                            ProductId = 5,
                            Url = "\\images\\products\\harbor_wireless_keyboard\\harbor_wireless_keyboard_04.png"
                        },
                        new
                        {
                            Id = 17,
                            DisplayOrder = 0,
                            ProductId = 6,
                            Url = "\\images\\products\\harbor_wireless_mouse\\harbor_wireless_mouse_01.png"
                        },
                        new
                        {
                            Id = 18,
                            DisplayOrder = 1,
                            ProductId = 6,
                            Url = "\\images\\products\\harbor_wireless_mouse\\harbor_wireless_mouse_02.png"
                        },
                        new
                        {
                            Id = 19,
                            DisplayOrder = 0,
                            ProductId = 7,
                            Url = "\\images\\products\\signal_usb_c_hub\\signal_usb_c_hub_01.png"
                        },
                        new
                        {
                            Id = 20,
                            DisplayOrder = 1,
                            ProductId = 7,
                            Url = "\\images\\products\\signal_usb_c_hub\\signal_usb_c_hub_02.png"
                        },
                        new
                        {
                            Id = 21,
                            DisplayOrder = 0,
                            ProductId = 8,
                            Url = "\\images\\products\\dockline_charging_station\\dockline_charging_station_01.png"
                        },
                        new
                        {
                            Id = 22,
                            DisplayOrder = 1,
                            ProductId = 8,
                            Url = "\\images\\products\\dockline_charging_station\\dockline_charging_station_02.png"
                        },
                        new
                        {
                            Id = 23,
                            DisplayOrder = 0,
                            ProductId = 9,
                            Url = "\\images\\products\\fold_storage_box_set\\fold_storage_box_set_01.png"
                        },
                        new
                        {
                            Id = 24,
                            DisplayOrder = 1,
                            ProductId = 9,
                            Url = "\\images\\products\\fold_storage_box_set\\fold_storage_box_set_02.png"
                        },
                        new
                        {
                            Id = 25,
                            DisplayOrder = 0,
                            ProductId = 10,
                            Url = "\\images\\products\\grid_drawer_organizer\\grid_drawer_organizer_01.png"
                        },
                        new
                        {
                            Id = 26,
                            DisplayOrder = 1,
                            ProductId = 10,
                            Url = "\\images\\products\\grid_drawer_organizer\\grid_drawer_organizer_02.png"
                        },
                        new
                        {
                            Id = 27,
                            DisplayOrder = 2,
                            ProductId = 10,
                            Url = "\\images\\products\\grid_drawer_organizer\\grid_drawer_organizer_03.png"
                        },
                        new
                        {
                            Id = 28,
                            DisplayOrder = 3,
                            ProductId = 10,
                            Url = "\\images\\products\\grid_drawer_organizer\\grid_drawer_organizer_04.png"
                        },
                        new
                        {
                            Id = 29,
                            DisplayOrder = 0,
                            ProductId = 11,
                            Url = "\\images\\products\\stack_document_tray\\stack_document_tray_01.png"
                        },
                        new
                        {
                            Id = 30,
                            DisplayOrder = 1,
                            ProductId = 11,
                            Url = "\\images\\products\\stack_document_tray\\stack_document_tray_02.png"
                        },
                        new
                        {
                            Id = 31,
                            DisplayOrder = 0,
                            ProductId = 12,
                            Url = "\\images\\products\\rail_wall_hook_rack\\rail_wall_hook_rack_01.png"
                        },
                        new
                        {
                            Id = 32,
                            DisplayOrder = 1,
                            ProductId = 12,
                            Url = "\\images\\products\\rail_wall_hook_rack\\rail_wall_hook_rack_02.png"
                        },
                        new
                        {
                            Id = 33,
                            DisplayOrder = 0,
                            ProductId = 13,
                            Url = "\\images\\products\\transit_carry_backpack\\transit_carry_backpack_01.png"
                        },
                        new
                        {
                            Id = 34,
                            DisplayOrder = 1,
                            ProductId = 13,
                            Url = "\\images\\products\\transit_carry_backpack\\transit_carry_backpack_02.png"
                        },
                        new
                        {
                            Id = 35,
                            DisplayOrder = 2,
                            ProductId = 13,
                            Url = "\\images\\products\\transit_carry_backpack\\transit_carry_backpack_03.png"
                        },
                        new
                        {
                            Id = 36,
                            DisplayOrder = 3,
                            ProductId = 13,
                            Url = "\\images\\products\\transit_carry_backpack\\transit_carry_backpack_04.png"
                        },
                        new
                        {
                            Id = 37,
                            DisplayOrder = 0,
                            ProductId = 14,
                            Url = "\\images\\products\\harbor_laptop_sleeve\\harbor_laptop_sleeve_01.png"
                        },
                        new
                        {
                            Id = 38,
                            DisplayOrder = 1,
                            ProductId = 14,
                            Url = "\\images\\products\\harbor_laptop_sleeve\\harbor_laptop_sleeve_02.png"
                        },
                        new
                        {
                            Id = 39,
                            DisplayOrder = 0,
                            ProductId = 15,
                            Url = "\\images\\products\\roam_travel_pouch\\roam_travel_pouch_01.png"
                        },
                        new
                        {
                            Id = 40,
                            DisplayOrder = 1,
                            ProductId = 15,
                            Url = "\\images\\products\\roam_travel_pouch\\roam_travel_pouch_02.png"
                        },
                        new
                        {
                            Id = 41,
                            DisplayOrder = 0,
                            ProductId = 16,
                            Url = "\\images\\products\\summit_insulated_bottle\\summit_insulated_bottle_01.png"
                        },
                        new
                        {
                            Id = 42,
                            DisplayOrder = 1,
                            ProductId = 16,
                            Url = "\\images\\products\\summit_insulated_bottle\\summit_insulated_bottle_02.png"
                        },
                        new
                        {
                            Id = 43,
                            DisplayOrder = 0,
                            ProductId = 17,
                            Url = "\\images\\products\\vale_ambient_lamp\\vale_ambient_lamp_01.png"
                        },
                        new
                        {
                            Id = 44,
                            DisplayOrder = 1,
                            ProductId = 17,
                            Url = "\\images\\products\\vale_ambient_lamp\\vale_ambient_lamp_02.png"
                        },
                        new
                        {
                            Id = 45,
                            DisplayOrder = 2,
                            ProductId = 17,
                            Url = "\\images\\products\\vale_ambient_lamp\\vale_ambient_lamp_03.png"
                        },
                        new
                        {
                            Id = 46,
                            DisplayOrder = 3,
                            ProductId = 17,
                            Url = "\\images\\products\\vale_ambient_lamp\\vale_ambient_lamp_04.png"
                        },
                        new
                        {
                            Id = 47,
                            DisplayOrder = 0,
                            ProductId = 18,
                            Url = "\\images\\products\\hearth_utility_tray\\hearth_utility_tray_01.png"
                        },
                        new
                        {
                            Id = 48,
                            DisplayOrder = 1,
                            ProductId = 18,
                            Url = "\\images\\products\\hearth_utility_tray\\hearth_utility_tray_02.png"
                        },
                        new
                        {
                            Id = 49,
                            DisplayOrder = 0,
                            ProductId = 19,
                            Url = "\\images\\products\\drift_throw_blanket\\drift_throw_blanket_01.png"
                        },
                        new
                        {
                            Id = 50,
                            DisplayOrder = 1,
                            ProductId = 19,
                            Url = "\\images\\products\\drift_throw_blanket\\drift_throw_blanket_02.png"
                        },
                        new
                        {
                            Id = 51,
                            DisplayOrder = 0,
                            ProductId = 20,
                            Url = "\\images\\products\\grove_reed_diffuser\\grove_reed_diffuser_01.png"
                        },
                        new
                        {
                            Id = 52,
                            DisplayOrder = 1,
                            ProductId = 20,
                            Url = "\\images\\products\\grove_reed_diffuser\\grove_reed_diffuser_02.png"
                        });
                });

            modelBuilder.Entity("Northstar.Models.ShoppingCartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Northstar.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("CompanyId");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("Northstar.Models.OrderHeader", b =>
                {
                    b.HasOne("Northstar.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Northstar.Models.OrderItemDetails", b =>
                {
                    b.HasOne("Northstar.Models.OrderHeader", "OrderHeader")
                        .WithMany()
                        .HasForeignKey("OrderHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Northstar.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderHeader");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Northstar.Models.Product", b =>
                {
                    b.HasOne("Northstar.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Northstar.Models.ProductImage", b =>
                {
                    b.HasOne("Northstar.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Northstar.Models.ShoppingCartItem", b =>
                {
                    b.HasOne("Northstar.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Northstar.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Northstar.Models.ApplicationUser", b =>
                {
                    b.HasOne("Northstar.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Northstar.Models.Product", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
